// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {AccessControlDefaultAdminRules} from "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import {Pausable} from "@openzeppelin/contracts/utils/Pausable.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title VerdexP2PEscrow
 * @notice Non-custodial-on-chain settlement escrow for a VDX-for-fiat P2P trade.
 * @dev Fiat payment evidence, KYC documents, names, phone numbers, chat and bank
 *      details MUST NOT be put on-chain. `tradeReference` is an opaque SHA-256
 *      reference generated by the private P2P service. The seller deposits VDX;
 *      the buyer marks an off-chain payment; the seller releases. A disputed
 *      escrow can move only when the configured number of distinct arbiters sign
 *      the same EIP-712 decision. The governance multisig can manage arbiters but
 *      cannot transfer an escrowed VDX balance by itself. Emergency pausers can
 *      freeze settlement, but cannot move VDX. Resuming settlement is a separate
 *      role intended for a governance timelock.
 */
contract VerdexP2PEscrow is AccessControlDefaultAdminRules, Pausable, ReentrancyGuard {
    using SafeERC20 for IERC20;
    using ECDSA for bytes32;

    bytes32 public constant ARBITER_ADMIN_ROLE = keccak256("ARBITER_ADMIN_ROLE");
    bytes32 public constant ARBITER_ROLE = keccak256("ARBITER_ROLE");
    bytes32 public constant TRADE_ATTESTOR_ADMIN_ROLE = keccak256("TRADE_ATTESTOR_ADMIN_ROLE");
    bytes32 public constant TRADE_ATTESTOR_ROLE = keccak256("TRADE_ATTESTOR_ROLE");
    bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE");
    bytes32 public constant UNPAUSER_ROLE = keccak256("UNPAUSER_ROLE");

    bytes32 private constant EIP712_DOMAIN_TYPEHASH = keccak256(
        "EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"
    );
    bytes32 private constant RESOLUTION_TYPEHASH = keccak256(
        "EscrowResolution(bytes32 escrowId,address recipient,uint256 resolutionNonce,uint256 deadline)"
    );
    bytes32 private constant TRADE_AUTHORIZATION_TYPEHASH = keccak256(
        "TradeAuthorization(address seller,address buyer,uint256 amount,uint64 paymentDeadline,bytes32 tradeReference,uint256 authorizationDeadline)"
    );
    bytes32 private constant NAME_HASH = keccak256("Verdex P2P Escrow");
    bytes32 private constant VERSION_HASH = keccak256("1");

    uint64 public constant MAX_PAYMENT_WINDOW = 7 days;
    uint64 public constant MAX_TRADE_AUTHORIZATION_VALIDITY = 30 minutes;
    uint64 public constant MAX_RESOLUTION_SIGNATURE_VALIDITY = 24 hours;
    uint48 public constant DEFAULT_ADMIN_TRANSFER_DELAY = 2 days;
    uint8 public constant MIN_ARBITRATION_QUORUM = 2;
    uint8 public constant MAX_ARBITRATION_QUORUM = 15;

    enum State {
        None,
        Funded,
        PaymentMarked,
        Disputed,
        Released,
        Refunded
    }

    struct Escrow {
        address seller;
        address buyer;
        uint256 amount;
        uint64 paymentDeadline;
        uint64 fundedAt;
        uint256 resolutionNonce;
        bytes32 tradeReference;
        State state;
    }

    IERC20 public immutable vdx;
    bytes32 public immutable DOMAIN_SEPARATOR;
    uint8 public arbitrationQuorum;
    uint256 public arbiterCount;
    uint256 private nextEscrowNonce;

    mapping(bytes32 escrowId => Escrow escrow) private escrows;
    mapping(bytes32 authorizationDigest => bool consumed) public consumedTradeAuthorizations;
    mapping(bytes32 tradeReference => bool used) public usedTradeReferences;

    error InvalidAddress();
    error InvalidAmount();
    error InvalidTradeReference();
    error InvalidPaymentDeadline();
    error InvalidEscrowState(State expected, State actual);
    error InvalidDisputeState(State actual);
    error NotEscrowBuyer();
    error NotEscrowSeller();
    error NotTradeParty();
    error PaymentWindowNotExpired();
    error PaymentWindowExpired();
    error TradeAuthorizationExpired();
    error InvalidTradeAuthorizationDeadline();
    error InvalidTradeAuthorization();
    error TradeAuthorizationAlreadyConsumed();
    error TradeReferenceAlreadyUsed();
    error InvalidArbitrationQuorum();
    error ArbitrationQuorumWouldBeBroken();
    error ResolutionSignatureExpired();
    error ResolutionSignatureDeadlineTooFar();
    error InvalidResolutionRecipient();
    error InvalidResolutionNonce();
    error DuplicateArbiterSignature();
    error InsufficientArbiterSignatures();
    error TooManyArbiterSignatures();
    error UnsupportedTokenBehaviour();

    event EscrowCreated(
        bytes32 indexed escrowId,
        bytes32 indexed tradeReference,
        address indexed seller,
        address buyer,
        uint256 amount,
        uint64 paymentDeadline
    );
    event PaymentMarked(bytes32 indexed escrowId, address indexed buyer);
    event DisputeOpened(bytes32 indexed escrowId, address indexed openedBy);
    event EscrowReleased(bytes32 indexed escrowId, address indexed buyer, uint256 amount, address settledBy);
    event EscrowRefunded(bytes32 indexed escrowId, address indexed seller, uint256 amount, address settledBy);
    event ArbitrationQuorumChanged(uint8 previousQuorum, uint8 newQuorum);
    event TradeAuthorizationConsumed(bytes32 indexed authorizationDigest, bytes32 indexed tradeReference, address indexed attestor);

    constructor(
        IERC20 vdx_,
        address governanceMultisig,
        address[] memory initialArbiters,
        address[] memory initialTradeAttestors,
        uint8 arbitrationQuorum_
    ) AccessControlDefaultAdminRules(DEFAULT_ADMIN_TRANSFER_DELAY, governanceMultisig) {
        if (address(vdx_) == address(0) || governanceMultisig == address(0)) revert InvalidAddress();
        if (
            arbitrationQuorum_ < MIN_ARBITRATION_QUORUM ||
            arbitrationQuorum_ > MAX_ARBITRATION_QUORUM ||
            initialArbiters.length < arbitrationQuorum_ ||
            initialTradeAttestors.length == 0
        ) revert InvalidArbitrationQuorum();

        vdx = vdx_;
        arbitrationQuorum = arbitrationQuorum_;
        DOMAIN_SEPARATOR = keccak256(
            abi.encode(
                EIP712_DOMAIN_TYPEHASH,
                NAME_HASH,
                VERSION_HASH,
                block.chainid,
                address(this)
            )
        );

        _grantRole(ARBITER_ADMIN_ROLE, governanceMultisig);
        _grantRole(TRADE_ATTESTOR_ADMIN_ROLE, governanceMultisig);
        _grantRole(PAUSER_ROLE, governanceMultisig);
        _grantRole(UNPAUSER_ROLE, governanceMultisig);
        _setRoleAdmin(ARBITER_ROLE, ARBITER_ADMIN_ROLE);
        _setRoleAdmin(TRADE_ATTESTOR_ROLE, TRADE_ATTESTOR_ADMIN_ROLE);

        for (uint256 i = 0; i < initialArbiters.length; ++i) {
            if (initialArbiters[i] == address(0)) revert InvalidAddress();
            if (!hasRole(ARBITER_ROLE, initialArbiters[i])) {
                _grantRole(ARBITER_ROLE, initialArbiters[i]);
                unchecked {
                    ++arbiterCount;
                }
            }
        }
        if (arbiterCount < arbitrationQuorum_) revert InvalidArbitrationQuorum();
        for (uint256 i = 0; i < initialTradeAttestors.length; ++i) {
            if (initialTradeAttestors[i] == address(0)) revert InvalidAddress();
            _grantRole(TRADE_ATTESTOR_ROLE, initialTradeAttestors[i]);
        }
    }

    /**
     * @notice Lock a seller's VDX for exactly one verified P2P trade.
     * @param buyer Buyer wallet, admitted by the off-chain KYC/P2P service.
     * @param amount VDX atomic units to escrow.
     * @param paymentDeadline Unix timestamp, at most seven days from now.
     * @param tradeReference Opaque, non-PII server-side trade reference hash.
     * @param authorizationDeadline Expiry of an in-house KYC/P2P service signature.
     * @param tradeAuthorization EIP-712 signature from a current TRADE_ATTESTOR_ROLE wallet.
     */
    function createEscrow(
        address buyer,
        uint256 amount,
        uint64 paymentDeadline,
        bytes32 tradeReference,
        uint256 authorizationDeadline,
        bytes calldata tradeAuthorization
    ) external whenNotPaused nonReentrant returns (bytes32 escrowId) {
        if (buyer == address(0) || buyer == msg.sender) revert InvalidAddress();
        if (amount == 0) revert InvalidAmount();
        if (tradeReference == bytes32(0)) revert InvalidTradeReference();
        if (paymentDeadline <= block.timestamp || paymentDeadline > block.timestamp + MAX_PAYMENT_WINDOW) {
            revert InvalidPaymentDeadline();
        }
        if (authorizationDeadline <= block.timestamp) revert TradeAuthorizationExpired();
        if (authorizationDeadline > block.timestamp + MAX_TRADE_AUTHORIZATION_VALIDITY) {
            revert InvalidTradeAuthorizationDeadline();
        }
        bytes32 authorizationDigest = tradeAuthorizationDigest(
            msg.sender, buyer, amount, paymentDeadline, tradeReference, authorizationDeadline
        );
        if (consumedTradeAuthorizations[authorizationDigest]) revert TradeAuthorizationAlreadyConsumed();
        if (usedTradeReferences[tradeReference]) revert TradeReferenceAlreadyUsed();
        address attestor = authorizationDigest.recover(tradeAuthorization);
        if (!hasRole(TRADE_ATTESTOR_ROLE, attestor)) revert InvalidTradeAuthorization();
        consumedTradeAuthorizations[authorizationDigest] = true;
        usedTradeReferences[tradeReference] = true;

        unchecked {
            ++nextEscrowNonce;
        }
        escrowId = keccak256(
            abi.encode(address(this), block.chainid, msg.sender, buyer, amount, paymentDeadline, tradeReference, nextEscrowNonce)
        );
        Escrow storage escrow = escrows[escrowId];
        escrow.seller = msg.sender;
        escrow.buyer = buyer;
        escrow.amount = amount;
        escrow.paymentDeadline = paymentDeadline;
        escrow.fundedAt = uint64(block.timestamp);
        escrow.tradeReference = tradeReference;
        escrow.state = State.Funded;

        uint256 balanceBefore = vdx.balanceOf(address(this));
        vdx.safeTransferFrom(msg.sender, address(this), amount);
        if (vdx.balanceOf(address(this)) - balanceBefore != amount) revert UnsupportedTokenBehaviour();

        emit EscrowCreated(escrowId, tradeReference, msg.sender, buyer, amount, paymentDeadline);
        emit TradeAuthorizationConsumed(authorizationDigest, tradeReference, attestor);
    }

    /** @notice The buyer confirms having sent the off-chain fiat payment. */
    function markPayment(bytes32 escrowId) external whenNotPaused {
        Escrow storage escrow = _escrowInState(escrowId, State.Funded);
        if (msg.sender != escrow.buyer) revert NotEscrowBuyer();
        if (block.timestamp > escrow.paymentDeadline) revert PaymentWindowExpired();
        escrow.state = State.PaymentMarked;
        emit PaymentMarked(escrowId, msg.sender);
    }

    /** @notice The seller releases escrowed VDX after independently verifying fiat receipt. */
    function release(bytes32 escrowId) external whenNotPaused nonReentrant {
        Escrow storage escrow = _escrowInState(escrowId, State.PaymentMarked);
        if (msg.sender != escrow.seller) revert NotEscrowSeller();
        escrow.state = State.Released;
        vdx.safeTransfer(escrow.buyer, escrow.amount);
        emit EscrowReleased(escrowId, escrow.buyer, escrow.amount, msg.sender);
    }

    /** @notice Return VDX to the seller only when the buyer did not mark payment in time. */
    function refundExpired(bytes32 escrowId) external whenNotPaused nonReentrant {
        Escrow storage escrow = _escrowInState(escrowId, State.Funded);
        if (block.timestamp <= escrow.paymentDeadline) revert PaymentWindowNotExpired();
        escrow.state = State.Refunded;
        vdx.safeTransfer(escrow.seller, escrow.amount);
        emit EscrowRefunded(escrowId, escrow.seller, escrow.amount, msg.sender);
    }

    /**
     * @notice Either trade party may freeze an in-flight escrow for human review.
     * @dev This remains available while paused so a party can protect a trade
     *      during an incident. It cannot transfer VDX.
     */
    function openDispute(bytes32 escrowId) external {
        Escrow storage escrow = escrows[escrowId];
        if (escrow.state != State.Funded && escrow.state != State.PaymentMarked) {
            revert InvalidDisputeState(escrow.state);
        }
        if (msg.sender != escrow.buyer && msg.sender != escrow.seller) revert NotTradeParty();
        escrow.state = State.Disputed;
        emit DisputeOpened(escrowId, msg.sender);
    }

    /**
     * @notice Settle a dispute from a threshold of independent EIP-712 arbiter signatures.
     * @dev Anyone may relay valid signatures. `recipient` must be the trade buyer or seller.
     */
    function resolveDispute(
        bytes32 escrowId,
        address recipient,
        uint256 resolutionNonce,
        uint256 signatureDeadline,
        bytes[] calldata signatures
    ) external whenNotPaused nonReentrant {
        Escrow storage escrow = _escrowInState(escrowId, State.Disputed);
        if (recipient != escrow.buyer && recipient != escrow.seller) revert InvalidResolutionRecipient();
        if (resolutionNonce != escrow.resolutionNonce) revert InvalidResolutionNonce();
        if (signatureDeadline <= block.timestamp) revert ResolutionSignatureExpired();
        if (signatureDeadline > block.timestamp + MAX_RESOLUTION_SIGNATURE_VALIDITY) {
            revert ResolutionSignatureDeadlineTooFar();
        }
        if (signatures.length < arbitrationQuorum) revert InsufficientArbiterSignatures();
        if (signatures.length > MAX_ARBITRATION_QUORUM) revert TooManyArbiterSignatures();

        bytes32 digest = resolutionDigest(escrowId, recipient, resolutionNonce, signatureDeadline);
        address[] memory signers = new address[](signatures.length);
        uint256 validSignatures;
        for (uint256 i = 0; i < signatures.length; ++i) {
            address signer = digest.recover(signatures[i]);
            if (!hasRole(ARBITER_ROLE, signer)) continue;
            for (uint256 j = 0; j < validSignatures; ++j) {
                if (signers[j] == signer) revert DuplicateArbiterSignature();
            }
            signers[validSignatures] = signer;
            unchecked {
                ++validSignatures;
            }
        }
        if (validSignatures < arbitrationQuorum) revert InsufficientArbiterSignatures();

        unchecked {
            ++escrow.resolutionNonce;
        }
        if (recipient == escrow.buyer) {
            escrow.state = State.Released;
            vdx.safeTransfer(recipient, escrow.amount);
            emit EscrowReleased(escrowId, recipient, escrow.amount, msg.sender);
        } else {
            escrow.state = State.Refunded;
            vdx.safeTransfer(recipient, escrow.amount);
            emit EscrowRefunded(escrowId, recipient, escrow.amount, msg.sender);
        }
    }

    function resolutionDigest(
        bytes32 escrowId,
        address recipient,
        uint256 resolutionNonce,
        uint256 signatureDeadline
    ) public view returns (bytes32) {
        bytes32 structHash = keccak256(
            abi.encode(RESOLUTION_TYPEHASH, escrowId, recipient, resolutionNonce, signatureDeadline)
        );
        return keccak256(abi.encodePacked("\x19\x01", DOMAIN_SEPARATOR, structHash));
    }

    function tradeAuthorizationDigest(
        address seller,
        address buyer,
        uint256 amount,
        uint64 paymentDeadline,
        bytes32 tradeReference,
        uint256 authorizationDeadline
    ) public view returns (bytes32) {
        bytes32 structHash = keccak256(
            abi.encode(
                TRADE_AUTHORIZATION_TYPEHASH,
                seller,
                buyer,
                amount,
                paymentDeadline,
                tradeReference,
                authorizationDeadline
            )
        );
        return keccak256(abi.encodePacked("\x19\x01", DOMAIN_SEPARATOR, structHash));
    }

    function getEscrow(bytes32 escrowId) external view returns (Escrow memory) {
        return escrows[escrowId];
    }

    /**
     * @notice Freeze all VDX-moving settlement paths during an incident.
     * @dev Pausers cannot unpause or transfer escrowed VDX. Assign this role to
     *      a dedicated incident-response principal after deployment.
     */
    function pause() external onlyRole(PAUSER_ROLE) {
        _pause();
    }

    /**
     * @notice Resume settlement after governance has reviewed the incident.
     * @dev This role is intentionally distinct from PAUSER_ROLE and should be
     *      held by the delayed governance/timelock authority.
     */
    function unpause() external onlyRole(UNPAUSER_ROLE) {
        _unpause();
    }

    function setArbitrationQuorum(uint8 newQuorum) external onlyRole(ARBITER_ADMIN_ROLE) {
        if (
            newQuorum < MIN_ARBITRATION_QUORUM ||
            newQuorum > MAX_ARBITRATION_QUORUM ||
            newQuorum > arbiterCount
        ) revert InvalidArbitrationQuorum();
        uint8 previousQuorum = arbitrationQuorum;
        arbitrationQuorum = newQuorum;
        emit ArbitrationQuorumChanged(previousQuorum, newQuorum);
    }

    function grantRole(bytes32 role, address account) public override(AccessControlDefaultAdminRules) {
        if (account == address(0)) revert InvalidAddress();
        bool isNewArbiter = role == ARBITER_ROLE && !hasRole(role, account);
        super.grantRole(role, account);
        if (isNewArbiter) {
            unchecked {
                ++arbiterCount;
            }
        }
    }

    function revokeRole(bytes32 role, address account) public override(AccessControlDefaultAdminRules) {
        bool isArbiter = role == ARBITER_ROLE && hasRole(role, account);
        if (isArbiter && arbiterCount <= arbitrationQuorum) {
            revert ArbitrationQuorumWouldBeBroken();
        }
        super.revokeRole(role, account);
        if (isArbiter) {
            unchecked {
                --arbiterCount;
            }
        }
    }

    function renounceRole(bytes32 role, address callerConfirmation) public override(AccessControlDefaultAdminRules) {
        bool isArbiter = role == ARBITER_ROLE && hasRole(role, callerConfirmation);
        if (isArbiter && arbiterCount <= arbitrationQuorum) {
            revert ArbitrationQuorumWouldBeBroken();
        }
        super.renounceRole(role, callerConfirmation);
        if (isArbiter && hasRole(role, callerConfirmation) == false) {
            unchecked {
                --arbiterCount;
            }
        }
    }

    function _escrowInState(bytes32 escrowId, State expected) private view returns (Escrow storage escrow) {
        escrow = escrows[escrowId];
        if (escrow.state != expected) revert InvalidEscrowState(expected, escrow.state);
    }
}
